model:
  type: 'poly'
  seed: 1
dir_raw_data: 'data/raw/temp/lorenz96/poly/lorenz96'
dir_out: 'models/temp/lorenz96/poly/'
dir_predictions: 'models/temp/lorenz96/poly/predictions/'
dir_results: 'models/temp/lorenz96/poly/results/'
data_loader: # Data loader
  test_mode: 'sequential_coupled_local' # 'batch'
  normalize: False
  batch_size: None
  seed: 1
  dir_store_ml_data: 'data/processed/temp/lorenz96/poly/'
