model:
  type: 'climatology'
  seed: 1
dir_raw_data: 'data/raw/temp/lorenz96/fcnn/lorenz96'
dir_out: 'models/temp/lorenz96/clim/'
dir_predictions: 'models/temp/lorenz96/clim/predictions/'
dir_results: 'models/temp/lorenz96/clim/results/'
data_loader: # Data loader
  test_mode: 'sequential_coupled_local'
  seed: 1